plugins {
    id 'com.github.node-gradle.node'
}

task installWithCI(type: NpmTask) {
    inputs.files "package.json"
    outputs.dir "./node_modules"
    // install with the ci command
    args = ['ci', '--ignore-scripts', '--quiet', '--target_arch=x64']
}

task npm_install(type: NpmTask) {
    // install with more arguments
    args = ['install', '--ignore-scripts', '--quiet', '--target_arch=x64']
}

task build(type: NpmTask,
        group: 'node',
        dependsOn: 'npmLint',
        description: 'Build frontend project'
    ) {
    args = ['run', 'build']
    inputs.dir '.'
    outputs.dir "../../build/resources/main"
}

task npmLint(
        type: NpmTask,
        group: 'node',
    dependsOn: 'installWithCI',
        description: 'Run frontend lint'
) {
    inputs.dir '.'
    outputs.dir "../../build/lint-results"
    args = ['run', 'lint']
}

task clean(type: NpmTask,
        group: 'node',
        description: 'Clean frontend project'
    ) {
    args = ['run', 'clean']
}

repositories {
    mavenLocal()
    mavenCentral()
}

node {
    version = '16.20.2'
    npmVersion = '8.19.4'
    download = true
}
